### ISSUE TITLE
bug: Generated command comportnent code has error in import statement when using TypeScript

### ISSUE THREAD

**Issue by Allianaab2m** [sapphiredev/cli#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When I generate a command component using the CLI, the type prefix is missing from the import statement, causing an error.
The other components (listener, arguments, precondition), this error did not occur.

### Steps To Reproduce

```
sapphire generate command [commandName]
```

### Expected behavior

It should generate code like this.
```ts
import { ApplyOptions } from '@sapphire/decorators';
import { SubCommandPluginCommand, SubCommandPluginCommandOptions } from '@sapphire/plugin-subcommands';
import type { Message } from 'discord.js';

@ApplyOptions<SubCommandPluginCommandOptions>({
	description: 'A basic command'
})
export class UserCommand extends SubCommandPluginCommand {
	public async messageRun(message: Message) {
		return message.channel.send('Hello world!');
	}
}
```

### Additional context

This is the first time for me to make an issue, and I used machine translation, 
so I really apologize if there are any confusing parts.

**Comment by UndiedGamer** [comment]
whats your templates/command.ts.sapphire file?
and can you show your file structure with command usage

**Comment by Allianaab2m** [comment]
I'm not sure, because I've just started using Sapphire, but I probably don't use template. 
In .sapphirerc.yml, customTemplate is set to false.
```yml:.sapphirerc.yml
projectLanguage: "ts"
locations:
  base: src
  arguments: arguments
  commands: commands
  listeners: listeners
  preconditions: preconditions
customFileTemplates:
  enabled: false
  location: ""
```
Here is the file structure of the project.
foo.ts is a component that I generated myself.
![image](https://user-images.githubusercontent.com/56180684/149739490-5735d989-0838-4d2a-ad5b-23a0fa40628a.png)
